export type HexTile = {
	id: string;
	q: number; // Axial coordinate (horizontal)
	r: number; // Axial coordinate (vertical)
	color: string; // CSS class name
	icon?: string; // Optional icon reference
};

export const boardData: HexTile[] = [
	// Col 1
	{ id: 'red-1', q: 0, r: 0, color: 'red' },
	{ id: 'red-2', q: 1, r: 0, color: 'red' },
	{ id: 'blank', q: 2, r: 0, color: 'white' },
	{ id: 'blank', q: 3, r: 0, color: 'white' },
	{ id: 'blank', q: 4, r: 0, color: 'white' },
	{ id: 'wall', q: 5, r: 0, color: 'black' },
	{ id: 'energy', q: 6, r: 0, color: 'white', icon: '⚡' },
	{ id: 'dbl_energy', q: 7, r: 0, color: 'white', icon: '⚡⚡' },
	{ id: 'energy', q: 8, r: 0, color: 'white', icon: '⚡' },
	{ id: 'wall', q: 9, r: 0, color: 'black' },
	{ id: 'blank', q: 10, r: 0, color: 'white' },
	{ id: 'blank', q: 11, r: 0, color: 'white' },
	{ id: 'blank', q: 12, r: 0, color: 'white' },
	{ id: 'purple-1', q: 13, r: 0, color: 'purple' },
	{ id: 'purple-2', q: 14, r: 0, color: 'purple' },

	// Col 2
	{ id: 'red-3', q: 0, r: 1, color: 'red' },
	{ id: 'red-4', q: -1, r: 1, color: 'red' },
	{ id: 'red-5', q: 1, r: 1, color: 'red' },
	{ id: 'blank', q: 2, r: 1, color: 'white' },
	{ id: 'blank', q: 3, r: 1, color: 'white' },
	{ id: 'wall', q: 4, r: 1, color: 'black' },
	{ id: 'blank', q: 3, r: 1, color: 'white' },
	{ id: 'wall', q: 4, r: 1, color: 'black' },
	{ id: 'energy', q: 5, r: 1, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 6, r: 1, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 7, r: 1, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 8, r: 1, color: 'white', icon: '⚡' },
	{ id: 'wall', q: 9, r: 1, color: 'black' },
	{ id: 'blank', q: 10, r: 1, color: 'white' },
	{ id: 'blank', q: 11, r: 1, color: 'white' },
	{ id: 'purple-3', q: 12, r: 1, color: 'purple' },
	{ id: 'purple-4', q: 13, r: 1, color: 'purple' },
	{ id: 'purple-5', q: 14, r: 1, color: 'purple' },

	// Col 3
	{ id: 'red-6', q: 0, r: 2, color: 'red' },
	{ id: 'red-7', q: 1, r: 2, color: 'red' },
	{ id: 'blank', q: 2, r: 2, color: 'white' },
	{ id: 'blank', q: 3, r: 2, color: 'white' },
	{ id: 'blank', q: 4, r: 2, color: 'white' },
	{ id: 'blank', q: 5, r: 2, color: 'white' },
	{ id: 'blank', q: 6, r: 2, color: 'white' },
	{ id: 'blank', q: 7, r: 2, color: 'white' },
	{ id: 'blank', q: 8, r: 2, color: 'white' },
	{ id: 'blank', q: 9, r: 2, color: 'white' },
	{ id: 'blank', q: 10, r: 2, color: 'white' },
	{ id: 'blank', q: 11, r: 2, color: 'white' },
	{ id: 'blank', q: 12, r: 2, color: 'white' },
	{ id: 'purple-6', q: 13, r: 2, color: 'purple' },
	{ id: 'purple-7', q: 14, r: 2, color: 'purple' },

	// Col 4

	{ id: 'blank', q: -1, r: 3, color: 'white' },
	{ id: 'blank', q: 0, r: 3, color: 'white' },
	{ id: 'blank', q: 1, r: 3, color: 'white' },
	{ id: 'blank', q: 2, r: 3, color: 'white' },
	{ id: 'blank', q: 3, r: 3, color: 'white' },
	{ id: 'blank', q: 4, r: 3, color: 'white' },
	{ id: 'blank', q: 5, r: 3, color: 'white' },
	{ id: 'blank', q: 6, r: 3, color: 'white' },
	{ id: 'blank', q: 7, r: 3, color: 'white' },
	{ id: 'blank', q: 8, r: 3, color: 'white' },
	{ id: 'blank', q: 9, r: 3, color: 'white' },
	{ id: 'blank', q: 10, r: 3, color: 'white' },
	{ id: 'blank', q: 11, r: 3, color: 'white' },
	{ id: 'blank', q: 12, r: 3, color: 'white' },
	{ id: 'blank', q: 13, r: 3, color: 'white' },
	{ id: 'blank', q: 14, r: 3, color: 'white' },

	// Col 5

	{ id: 'blank', q: 0, r: 4, color: 'white' },
	{ id: 'blank', q: 1, r: 4, color: 'white' },
	{ id: 'blank', q: 2, r: 4, color: 'white' },
	{ id: 'blank', q: 3, r: 4, color: 'white' },
	{ id: 'blank', q: 4, r: 4, color: 'white' },
	{ id: 'blank', q: 5, r: 4, color: 'white' },
	{ id: 'blank', q: 6, r: 4, color: 'white' },
	{ id: 'wall', q: 7, r: 4, color: 'black' },
	{ id: 'blank', q: 8, r: 4, color: 'white' },
	{ id: 'blank', q: 9, r: 4, color: 'white' },
	{ id: 'blank', q: 10, r: 4, color: 'white' },
	{ id: 'blank', q: 11, r: 4, color: 'white' },
	{ id: 'blank', q: 12, r: 4, color: 'white' },
	{ id: 'blank', q: 13, r: 4, color: 'white' },
	{ id: 'blank', q: 14, r: 4, color: 'white' },

	// Col 6

	{ id: 'wall', q: -1, r: 5, color: 'black' },
	{ id: 'blank', q: 0, r: 5, color: 'white' },
	{ id: 'blank', q: 1, r: 5, color: 'white' },
	{ id: 'blank', q: 2, r: 5, color: 'white' },
	{ id: 'blank', q: 3, r: 5, color: 'white' },
	{ id: 'blank', q: 4, r: 5, color: 'white' },
	{ id: 'wall', q: 5, r: 5, color: 'black' },
	{ id: 'wall', q: 6, r: 5, color: 'black' },
	{ id: 'wall', q: 7, r: 5, color: 'black' },
	{ id: 'wall', q: 8, r: 5, color: 'black' },
	{ id: 'blank', q: 9, r: 5, color: 'white' },
	{ id: 'blank', q: 10, r: 5, color: 'white' },
	{ id: 'blank', q: 11, r: 5, color: 'white' },
	{ id: 'blank', q: 12, r: 5, color: 'white' },
	{ id: 'blank', q: 13, r: 5, color: 'white' },
	{ id: 'wall', q: 14, r: 5, color: 'black' },

	// Col 7

	{ id: 'wall', q: 0, r: 6, color: 'black' },
	{ id: 'blank', q: 1, r: 6, color: 'white' },
	{ id: 'blank', q: 2, r: 6, color: 'white' },
	{ id: 'blank', q: 3, r: 6, color: 'white' },
	{ id: 'blank', q: 4, r: 6, color: 'white' },
	{ id: 'blank', q: 5, r: 6, color: 'white' },
	{ id: 'blank', q: 6, r: 6, color: 'white' },
	{ id: 'blank', q: 7, r: 6, color: 'white' },
	{ id: 'blank', q: 8, r: 6, color: 'white', icon: '🎲' },
	{ id: 'wall', q: 9, r: 6, color: 'black' },
	{ id: 'blank', q: 10, r: 6, color: 'white' },
	{ id: 'blank', q: 11, r: 6, color: 'white' },
	{ id: 'blank', q: 12, r: 6, color: 'white' },
	{ id: 'blank', q: 13, r: 6, color: 'white' },
	{ id: 'wall', q: 14, r: 6, color: 'black' },

	// Col 8

	{ id: 'energy', q: -1, r: 7, color: 'white', icon: '⚡' },
	{ id: 'blank', q: 0, r: 7, color: 'white' },
	{ id: 'blank', q: 1, r: 7, color: 'white' },
	{ id: 'blank', q: 2, r: 7, color: 'white' },
	{ id: 'blank', q: 3, r: 7, color: 'white' },
	{ id: 'wall', q: 4, r: 7, color: 'black' },
	{ id: 'blank', q: 5, r: 7, color: 'white', icon: '🎲' },
	{ id: 'energy', q: 6, r: 7, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 7, r: 7, color: 'white', icon: '⚡' },
	{ id: 'blank', q: 8, r: 7, color: 'white' },
	{ id: 'blank', q: 9, r: 7, color: 'white' },
	{ id: 'blank', q: 10, r: 7, color: 'white' },
	{ id: 'blank', q: 11, r: 7, color: 'white' },
	{ id: 'blank', q: 12, r: 7, color: 'white' },
	{ id: 'blank', q: 13, r: 7, color: 'white' },
	{ id: 'energy', q: 14, r: 7, color: 'white', icon: '⚡' },

	// Col 9

	{ id: 'energy', q: 0, r: 8, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 1, r: 8, color: 'white', icon: '⚡' },
	{ id: 'wall', q: 2, r: 8, color: 'black' },
	{ id: 'blank', q: 3, r: 8, color: 'white', icon: '🎲' },
	{ id: 'wall', q: 4, r: 8, color: 'black' },
	{ id: 'blank', q: 5, r: 8, color: 'white' },
	{ id: 'dbl_energy', q: 6, r: 8, color: 'white', icon: '⚡⚡' },
	{ id: 'dbl_energy', q: 7, r: 8, color: 'white', icon: '⚡⚡' },
	{ id: 'dbl_energy', q: 8, r: 8, color: 'white', icon: '⚡⚡' },
	{ id: 'blank', q: 9, r: 8, color: 'white' },
	{ id: 'wall', q: 10, r: 8, color: 'black' },
	{ id: 'blank', q: 11, r: 8, color: 'white', icon: '🎲' },
	{ id: 'wall', q: 12, r: 8, color: 'black' },
	{ id: 'energy', q: 13, r: 8, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 14, r: 8, color: 'white', icon: '⚡' },

	// Col 10

	{ id: 'energy', q: -1, r: 9, color: 'white', icon: '⚡' },
	{ id: 'blank', q: 0, r: 9, color: 'white' },
	{ id: 'blank', q: 1, r: 9, color: 'white' },
	{ id: 'blank', q: 2, r: 9, color: 'white' },
	{ id: 'blank', q: 3, r: 9, color: 'white' },
	{ id: 'blank', q: 4, r: 9, color: 'white' },
	{ id: 'blank', q: 5, r: 9, color: 'white' },
	{ id: 'energy', q: 6, r: 9, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 7, r: 9, color: 'white', icon: '⚡' },
	{ id: 'blank', q: 8, r: 9, color: 'white', icon: '🎲' },
	{ id: 'wall', q: 9, r: 9, color: 'black' },
	{ id: 'blank', q: 10, r: 9, color: 'white' },
	{ id: 'blank', q: 11, r: 9, color: 'white' },
	{ id: 'blank', q: 12, r: 9, color: 'white' },
	{ id: 'blank', q: 13, r: 9, color: 'white' },
	{ id: 'energy', q: 14, r: 9, color: 'white', icon: '⚡' },

	// Col 11

	{ id: 'wall', q: 0, r: 10, color: 'black' },
	{ id: 'blank', q: 1, r: 10, color: 'white' },
	{ id: 'blank', q: 2, r: 10, color: 'white' },
	{ id: 'blank', q: 3, r: 10, color: 'white' },
	{ id: 'blank', q: 4, r: 10, color: 'white' },
	{ id: 'wall', q: 5, r: 10, color: 'black' },
	{ id: 'blank', q: 6, r: 10, color: 'white', icon: '🎲' },
	{ id: 'blank', q: 7, r: 10, color: 'white' },
	{ id: 'blank', q: 8, r: 10, color: 'white' },
	{ id: 'blank', q: 9, r: 10, color: 'white' },
	{ id: 'blank', q: 10, r: 10, color: 'white' },
	{ id: 'blank', q: 11, r: 10, color: 'white' },
	{ id: 'blank', q: 12, r: 10, color: 'white' },
	{ id: 'blank', q: 13, r: 10, color: 'white' },
	{ id: 'wall', q: 14, r: 10, color: 'black' },

	// Col 12

	{ id: 'wall', q: -1, r: 11, color: 'black' },
	{ id: 'blank', q: 0, r: 11, color: 'white' },
	{ id: 'blank', q: 1, r: 11, color: 'white' },
	{ id: 'blank', q: 2, r: 11, color: 'white' },
	{ id: 'blank', q: 3, r: 11, color: 'white' },
	{ id: 'blank', q: 4, r: 11, color: 'white' },
	{ id: 'wall', q: 5, r: 11, color: 'black' },
	{ id: 'wall', q: 6, r: 11, color: 'black' },
	{ id: 'wall', q: 7, r: 11, color: 'black' },
	{ id: 'wall', q: 8, r: 11, color: 'black' },
	{ id: 'blank', q: 9, r: 11, color: 'white' },
	{ id: 'blank', q: 10, r: 11, color: 'white' },
	{ id: 'blank', q: 11, r: 11, color: 'white' },
	{ id: 'blank', q: 12, r: 11, color: 'white' },
	{ id: 'blank', q: 13, r: 11, color: 'white' },
	{ id: 'wall', q: 14, r: 11, color: 'black' },

	// Col 13

	{ id: 'blank', q: 0, r: 12, color: 'white' },
	{ id: 'blank', q: 1, r: 12, color: 'white' },
	{ id: 'blank', q: 2, r: 12, color: 'white' },
	{ id: 'blank', q: 3, r: 12, color: 'white' },
	{ id: 'blank', q: 4, r: 12, color: 'white' },
	{ id: 'blank', q: 5, r: 12, color: 'white' },
	{ id: 'blank', q: 6, r: 12, color: 'white' },
	{ id: 'wall', q: 7, r: 12, color: 'black' },
	{ id: 'blank', q: 8, r: 12, color: 'white' },
	{ id: 'blank', q: 9, r: 12, color: 'white' },
	{ id: 'blank', q: 10, r: 12, color: 'white' },
	{ id: 'blank', q: 11, r: 12, color: 'white' },
	{ id: 'blank', q: 12, r: 12, color: 'white' },
	{ id: 'blank', q: 13, r: 12, color: 'white' },
	{ id: 'blank', q: 14, r: 12, color: 'white' },

	// Col 14

	{ id: 'blank', q: -1, r: 13, color: 'white' },
	{ id: 'blank', q: 0, r: 13, color: 'white' },
	{ id: 'blank', q: 1, r: 13, color: 'white' },
	{ id: 'blank', q: 2, r: 13, color: 'white' },
	{ id: 'blank', q: 3, r: 13, color: 'white' },
	{ id: 'blank', q: 4, r: 13, color: 'white' },
	{ id: 'blank', q: 5, r: 13, color: 'white' },
	{ id: 'blank', q: 6, r: 13, color: 'white' },
	{ id: 'blank', q: 7, r: 13, color: 'white' },
	{ id: 'blank', q: 8, r: 13, color: 'white' },
	{ id: 'blank', q: 9, r: 13, color: 'white' },
	{ id: 'blank', q: 10, r: 13, color: 'white' },
	{ id: 'blank', q: 11, r: 13, color: 'white' },
	{ id: 'blank', q: 12, r: 13, color: 'white' },
	{ id: 'blank', q: 13, r: 13, color: 'white' },
	{ id: 'blank', q: 14, r: 13, color: 'white' },

	// Col 15

	{ id: 'blue-1', q: 0, r: 14, color: 'blue' },
	{ id: 'blue-2', q: 1, r: 14, color: 'blue' },
	{ id: 'blank', q: 2, r: 14, color: 'white' },
	{ id: 'blank', q: 3, r: 14, color: 'white' },
	{ id: 'blank', q: 4, r: 14, color: 'white' },
	{ id: 'blank', q: 5, r: 14, color: 'white' },
	{ id: 'blank', q: 6, r: 14, color: 'white' },
	{ id: 'blank', q: 7, r: 14, color: 'white' },
	{ id: 'blank', q: 8, r: 14, color: 'white' },
	{ id: 'blank', q: 9, r: 14, color: 'white' },
	{ id: 'blank', q: 10, r: 14, color: 'white' },
	{ id: 'blank', q: 11, r: 14, color: 'white' },
	{ id: 'blank', q: 12, r: 14, color: 'white' },
	{ id: 'green-1', q: 13, r: 14, color: 'green' },
	{ id: 'green-2', q: 14, r: 14, color: 'green' },

	// Col 16
	{ id: 'blue-3', q: -1, r: 15, color: 'blue' },
	{ id: 'blue-4', q: 0, r: 15, color: 'blue' },
	{ id: 'blue-5', q: 1, r: 15, color: 'blue' },
	{ id: 'blank', q: 2, r: 15, color: 'white' },
	{ id: 'blank', q: 3, r: 15, color: 'white' },
	{ id: 'wall', q: 4, r: 15, color: 'black' },
	{ id: 'energy', q: 5, r: 15, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 6, r: 15, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 7, r: 15, color: 'white', icon: '⚡' },
	{ id: 'energy', q: 8, r: 15, color: 'white', icon: '⚡' },
	{ id: 'wall', q: 9, r: 15, color: 'black' },
	{ id: 'blank', q: 10, r: 15, color: 'white' },
	{ id: 'blank', q: 11, r: 15, color: 'white' },
	{ id: 'green-3', q: 12, r: 15, color: 'green' },
	{ id: 'green-4', q: 13, r: 15, color: 'green' },
	{ id: 'green-5', q: 14, r: 15, color: 'green' },

	// Col 17
	{ id: 'blue-6', q: 0, r: 16, color: 'blue' },
	{ id: 'blue-7', q: 1, r: 16, color: 'blue' },
	{ id: 'blank', q: 2, r: 16, color: 'white' },
	{ id: 'blank', q: 3, r: 16, color: 'white' },
	{ id: 'blank', q: 4, r: 16, color: 'white' },
	{ id: 'wall', q: 5, r: 16, color: 'black' },
	{ id: 'energy', q: 6, r: 16, color: 'white', icon: '⚡' },
	{ id: 'dbl_energy', q: 7, r: 16, color: 'white', icon: '⚡⚡' },
	{ id: 'energy', q: 8, r: 16, color: 'white', icon: '⚡' },
	{ id: 'wall', q: 9, r: 16, color: 'black' },
	{ id: 'blank', q: 10, r: 16, color: 'white' },
	{ id: 'blank', q: 11, r: 16, color: 'white' },
	{ id: 'blank', q: 12, r: 16, color: 'white' },
	{ id: 'green-6', q: 13, r: 16, color: 'green' },
	{ id: 'green-7', q: 14, r: 16, color: 'green' }
];
